name: Run Coverage
on:
  push:
    branches: [main]
    paths:
      - packages/lambda/**

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: packages-${{ hashFiles('**/yarn.lock') }}

      - run: npx lerna bootstrap
      - run: npx lerna run test -- --ci
      - run: bash <(curl -s https://codecov.io/bash)
