name: Run Lint Tool
on:
  pull_request:
    paths: 
      - packages/lambda/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: packages-${{ hashFiles('**/yarn.lock') }}

      - run: npx lerna bootstrap
      - run: npx lerna run lint
   
